begin;

alter table public.storefront_orders
  add column if not exists payment_confirmed_at timestamptz,
  add column if not exists payment_confirmed_by_user_id uuid;

create index if not exists idx_storefront_orders_payment_confirmed_at
  on public.storefront_orders (payment_confirmed_at);

create index if not exists idx_storefront_orders_payment_confirmed_by_user_id
  on public.storefront_orders (payment_confirmed_by_user_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'storefront_orders_payment_confirmed_by_user_id_fkey'
      and conrelid = 'public.storefront_orders'::regclass
  ) then
    alter table public.storefront_orders
      add constraint storefront_orders_payment_confirmed_by_user_id_fkey
      foreign key (payment_confirmed_by_user_id)
      references auth.users (id)
      on delete set null;
  end if;
end $$;

create table if not exists public.storefront_order_unit_assignments (
  id integer generated by default as identity primary key,
  order_item_id integer not null references public.storefront_order_items (id) on delete cascade,
  stock_unit_id integer not null references public.stock_units (id) on delete restrict,
  assigned_at timestamptz not null default now(),
  assigned_by_user_id uuid null references auth.users (id) on delete set null
);

create unique index if not exists idx_storefront_order_unit_assignments_order_item_stock
  on public.storefront_order_unit_assignments (order_item_id, stock_unit_id);

create unique index if not exists idx_storefront_order_unit_assignments_stock_unit_unique
  on public.storefront_order_unit_assignments (stock_unit_id);

create index if not exists idx_storefront_order_unit_assignments_order_item
  on public.storefront_order_unit_assignments (order_item_id);

create index if not exists idx_storefront_order_unit_assignments_assigned_by
  on public.storefront_order_unit_assignments (assigned_by_user_id);

commit;
